// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3853.CompetitionRobot20160120.subsystems;

import org.usfirst.frc3853.CompetitionRobot20160120.RobotMap;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class BallHandler extends Subsystem {

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  private final SpeedController motor = RobotMap.ballHandlerMotor;
  private final DigitalInput limitSwitchBallHandler = RobotMap.ballHandlerLimitSwitchBallHandler;

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS\
  // Joystick stick = new Joystick(0);
  // Preferences prefs;

  // Put methods for controlling this subsystem
  // here. Call these from Commands.

  @Override
  public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // Set the default command for a subsystem here.
    // setDefaultCommand(new MySpecialCommand());
  }

  public BallHandler() {
    // LiveWindow.addActuator("BallHandler", "frontMotor", );
  }

  public void limitSwitchballhander() {
    motor.set(.5);

  }

  public void Load() {
    // double backup = 0;
    // double speed = prefs.getDouble("BallGrabSpeed", backup);
    motor.set(1);
    SmartDashboard.putNumber("BallLoad", 1);
  }

  public void Shoot() {
    // double backup = 0;
    // double speed = prefs.getDouble("BallShootSpeed", backup);
    motor.set(-1);
    SmartDashboard.putNumber("BallShoot", -1);
  }

  public void Release() {
    motor.set(-0.1);
    SmartDashboard.putNumber("BallRelease", -0.1);
  }

  public void stop() {
    motor.set(0);
    SmartDashboard.putNumber("BallStop", 0);
  }

  public boolean limitSwitchBallHandler() {
    // TODO Auto-generated method stub
    return !limitSwitchBallHandler.get();
  }

  public void sdData() {
    SmartDashboard.putBoolean("BallSwitch", limitSwitchBallHandler.get());
    SmartDashboard.putNumber("BallMotorSpeed", motor.get());
  }
}
