// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3853.CompetitionRobot20160120.subsystems;

import org.usfirst.frc3853.CompetitionRobot20160120.RobotMap;
import org.usfirst.frc3853.CompetitionRobot20160120.commands.DriveTeleop;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class DriveTrain extends Subsystem {

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  private final SpeedController rightMotor = RobotMap.DriveTrainRightMotor;
  private final SpeedController leftMotor = RobotMap.DriveTrainLeftMotor;
  private final RobotDrive robotDrive21 = RobotMap.DriveTrainRobotDrive21;
  private final Encoder driveTrainEncoderRight = RobotMap.DriveTrainDriveTrainEncoderRight;
  private final Encoder driveTrainEncoderLeft = RobotMap.DriveTrainDriveTrainEncoderLeft;

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  // Add by hand because robot builder wouldn't let us do it.

  // Initialize your subsystem here
  public DriveTrain() {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // Use these to get going:
    // setSetpoint() - Sets where the PID controller should move the system
    // to
    // enable() - Enables the PID controller.
    robotDrive21.stopMotor();
  }

  @Override
  public void initDefaultCommand() {
    setDefaultCommand(new DriveTeleop());
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

  // Set the default command for a subsystem here.
  // setDefaultCommand(new MySpecialCommand());
  public void RobotDrive21(Joystick joystick1, Joystick joystick2) {
    robotDrive21.arcadeDrive(joystick1, true);
  }

  protected double returnPIDInput() {
    // Return your input value for the PID loop
    // e.g. a sensor, like a potentiometer:
    // yourPot.getAverageVoltage() / kYourMaxVoltage;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    return driveTrainEncoderRight.pidGet();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
  }

  // protected void usePIDOutput(double output) {
  // Use output to drive your system, like a motor
  // e.g. yourMotor.set(output);

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
  // rightMotor.pidWrite(output);

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
  // }

  // public void Drive(double left,double right){
  // robotDrive21.tankDrive(left, right);

  // }
  public void Drive(Joystick Joystick1) {
    robotDrive21.arcadeDrive(Joystick1);

  }

  public void TDrive(Joystick Joystick1, Joystick Joystick2) {
    robotDrive21.tankDrive(Joystick1, Joystick2);

  }

  public void left() {
    leftMotor.set(0.5);
    rightMotor.set(-0.5);
  }

  public void right() {
    leftMotor.set(-0.5);
    rightMotor.set(0.5);
  }

  public void stop() {
    robotDrive21.stopMotor();
  }

  public void DriveFoward(double speed) {
    robotDrive21.arcadeDrive(speed, speed);
    robotDrive21.tankDrive(speed, speed);
  }

  public double getRightEncoder() {
    return this.driveTrainEncoderRight.getDistance();
  }

  public double getLeftEncoder() {
    return this.driveTrainEncoderLeft.getDistance();

  }

  public void sdData() {
    SmartDashboard.putNumber("Drive Left Encoder", driveTrainEncoderLeft.get());
    SmartDashboard.putNumber("Drive Right Encoder", driveTrainEncoderRight.get());
  }

}
